// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiTiPetro.Data;

namespace SiTiPetro.Migrations.Aplikasi
{
    [DbContext(typeof(AplikasiContext))]
    [Migration("20201216053152_AddRencanaWeightFactor")]
    partial class AddRencanaWeightFactor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SiTiPetro.Models.Aplikasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeveloperdevId")
                        .HasColumnType("int");

                    b.Property<string>("ba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departermen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deskripsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direktorat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("jenis_aplikasi")
                        .HasColumnType("int");

                    b.Property<string>("kompartemen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomer_hp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomor_surat_dof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pengerjaan")
                        .HasColumnType("int");

                    b.Property<string>("pic_ti_pi_pg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pic_unit_terkait")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rencana_anggaran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahun")
                        .HasColumnType("int");

                    b.Property<string>("upload_brd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperdevId");

                    b.ToTable("Aplikasi");
                });

            modelBuilder.Entity("SiTiPetro.Models.Developer", b =>
                {
                    b.Property<int>("devId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("aplikasiId")
                        .HasColumnType("int");

                    b.Property<string>("nama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("devId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("SiTiPetro.Models.RencanaKurva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bulan")
                        .HasColumnType("int");

                    b.Property<int>("Minggu")
                        .HasColumnType("int");

                    b.Property<double>("Presentasi")
                        .HasColumnType("float");

                    b.Property<double>("Realisasi")
                        .HasColumnType("float");

                    b.Property<double>("RencanProgres")
                        .HasColumnType("float");

                    b.Property<int>("aplikasiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RencanaKurva");
                });

            modelBuilder.Entity("SiTiPetro.Models.RencanaTimeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AplikasiId")
                        .HasColumnType("int");

                    b.Property<string>("BrdDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrdDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosingDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosingDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesainPrototypeDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesainPrototypeDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EutDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EutDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalBrdDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalBrdDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoLiveDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoLiveDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PengadaanDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PengadaanDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PengembanganDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PengembanganDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportDate2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestingDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestingDate2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AplikasiId")
                        .IsUnique();

                    b.ToTable("RencanaTimeline");
                });

            modelBuilder.Entity("SiTiPetro.Models.Aplikasi", b =>
                {
                    b.HasOne("SiTiPetro.Models.Developer", null)
                        .WithMany("aplikasi")
                        .HasForeignKey("DeveloperdevId");
                });

            modelBuilder.Entity("SiTiPetro.Models.RencanaTimeline", b =>
                {
                    b.HasOne("SiTiPetro.Models.Aplikasi", null)
                        .WithOne("rencanaTimeline")
                        .HasForeignKey("SiTiPetro.Models.RencanaTimeline", "AplikasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
